version: "3.4"
services:
  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=eidolon_test_task_db
    ports:
      - 7432:5432
