version: "3.4"
services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - flyway
    environment:
      - spring.r2dbc.url=r2dbc:postgresql://db/eidolon_test_task_db
      - spring.r2dbc.password=test
      - spring.r2dbc.username=test
      - server.error.include-message=always
    ports:
      - 8080:8080
    networks:
      - eidolon-network

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/eidolon_test_task_db -schemas=public -user=test -password=test -connectRetries=60 migrate
    volumes:
      - ./migrations/scripts:/flyway/sql
    networks:
      - eidolon-network

  db:
    image: postgres:15.0
    container_name: db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=eidolon_test_task_db
    ports:
      - 5432:5432
    networks:
      - eidolon-network

networks:
  eidolon-network:
    driver: bridge